name: Deploy

on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: switch_working_directory
        run: ls
      - id: switch_working_directory
        run: cd api
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: stephenmo/lyngua:latest
      - id: switch_working_directory_back
        run: cd ..
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  build:
    name: Hello_world_action
    runs-on: ubuntu-latest
    steps:
      - id: npm_build
        run: sh build.sh

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob upload-batch --connection-string ${{ secrets.AZURE_STORAGE }} -d '$web' -s dist
            az webapp restart --name ${{ secrets.WEBAPP_NAME }} --resource-group ${{ secrets.WEBAPP_RG }}
